### ISSUE TITLE
Let's keep Cypress and Angular up-to-date here

### ISSUE THREAD

**Issue by bahmutov** [muratkeremozcan/angular-playground#5]
- add a version badge to show the current Cypress version so the people know
- add renovate settings file to upgrade Cypress and main Angular libraries

**Comment by muratkeremozcan** [comment]
It looks like it is working.

https://github.com/muratkeremozcan/angular-playground/issues/6

@bahmutov does this resolve our issue?

**Comment by muratkeremozcan** [comment]
@bahmutov looks like it worked pretty well!

Do we keep the issue open?
